### ISSUE TITLE
Crash game, now I dont have a report, but assap i Update 

### ISSUE THREAD

**Issue by polloperrocampero** [moidu21/conveyorbeltmod#1]
Many times when I get close to a belt of this mod, the game crashes. I'm trying to migrate my entire world to v6 and the belt is the only thing missing.

**Comment by moidu21** [comment]
i don't get any trouble like that on U5 or after updating to u6 and i need more information to do something can you provide me your latest log when it crash it's maybe a mod interaction

**Comment by polloperrocampero** [comment]
Hi, this is the last fail log



Version: 188609, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000268

FactoryGame_Engine_Win64_Shipping!UGameInstance::CreateGameModeForURL() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\GameInstance.cpp:1203]
FactoryGame_Engine_Win64_Shipping!UWorld::SetGameMode() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\World.cpp:4256]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:13163]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:32]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12465]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12628]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1794]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by moidu21** [comment]
there is nothing in log related to my mod maybe you should try to verify your game file 
does it always crash when near my belt ?
if yes please send me your save game and your smm profile in private message on discord like that i can replicate the issue

**Comment by polloperrocampero** [comment]
hey! After your august udpdate it's more stable I think. ;aybe the creashes of the game now has to do with another mod or with a set of mods. It may also be that my game is corrupted, since every time I disconnect my body appears sleeping where it stayed, but I appear in the hub
