### ISSUE TITLE
Convoyer invisible sur une longue distance

### ISSUE THREAD

**Issue by Timikana** [moidu21/conveyorbeltmod#6]
Heylow,

j'ai un soucis sur des convoyer longue distance je ne les vois pas et par conséquent je ne peux les UP, ou les supprimer.

par ailleurs le MK6 bug, quand on remplace la structure par celle si, il n'y a aucun item qui circule dessue. je dois reconstruire la ligne complète. ( non tester avec les autres MK7+)

EN:
I'm having an issue with long-distance conveyors. I can't see them, and therefore I can't upgrade or delete them.

Also, the MK6 is buggy. When I replace the structure with it, no items circulate on it. I have to rebuild the entire line. (I haven't tested this with the other MK7+).

**Comment by moidu21** [comment]
merci pour ce retour 
je vais essayer de reproduire et corriger ce problème rapidement

**Comment by Timikana** [comment]
pas de problème j'ai remarqué quand j'ai commencé à supprimer des convoyer, qu'ils ont aussi réapparus
je peux donner la mains sur mon serveur y a pas de problème.
